#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-envs
Version  : 1.4
Release  : 27
URL      : https://files.pythonhosted.org/packages/3c/7f/2098df91ff1499860935b4276ea0c27d3234170b03f803a8b9c97e42f0e9/envs-1.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/3c/7f/2098df91ff1499860935b4276ea0c27d3234170b03f803a8b9c97e42f0e9/envs-1.4.tar.gz
Summary  : Easy access of environment variables from Python with support for strings, booleans, list, tuples, and dicts.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-envs-bin = %{version}-%{release}
Requires: pypi-envs-license = %{version}-%{release}
Requires: pypi-envs-python = %{version}-%{release}
Requires: pypi-envs-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: envs
Provides: envs-python
Provides: envs-python3
BuildRequires : pypi(poetry_core)

%description
No detailed description available

%package bin
Summary: bin components for the pypi-envs package.
Group: Binaries
Requires: pypi-envs-license = %{version}-%{release}

%description bin
bin components for the pypi-envs package.


%package license
Summary: license components for the pypi-envs package.
Group: Default

%description license
license components for the pypi-envs package.


%package python
Summary: python components for the pypi-envs package.
Group: Default
Requires: pypi-envs-python3 = %{version}-%{release}

%description python
python components for the pypi-envs package.


%package python3
Summary: python3 components for the pypi-envs package.
Group: Default
Requires: python3-core
Provides: pypi(envs)

%description python3
python3 components for the pypi-envs package.


%prep
%setup -q -n envs-1.4
cd %{_builddir}/envs-1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641434536
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-envs
cp %{_builddir}/envs-1.4/LICENSE %{buildroot}/usr/share/package-licenses/pypi-envs/92170cdc034b2ff819323ff670d3b7266c8bffcd
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/envs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-envs/92170cdc034b2ff819323ff670d3b7266c8bffcd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
